### ISSUE TITLE
Issue when running gite

### ISSUE THREAD

**Issue by adityakeyal** [abhisheksarkar30/git-extras-tool#2]
![image](https://user-images.githubusercontent.com/2504556/65815574-d1df4280-e20e-11e9-9c96-cd2f1de7ed3e.png)

![image](https://user-images.githubusercontent.com/2504556/65815577-df94c800-e20e-11e9-81f1-7169e73c0b9e.png)

**Comment by abhisheksarkar30** [comment]
It seems there can be following root-causes to this problem:
1. If bson / pymongo package is installed, then their installation should be in the mentioned order. Reference : [https://github.com/py-bson/bson/issues/82#issuecomment-465664800](https://github.com/py-bson/bson/issues/82#issuecomment-465664800)
2. As per the attached screenshot, pkgutil package is pointed to python2.7, I think if its updated to latest, it will solve the problem. Reference: [https://github.com/sphinx-doc/sphinx/issues/4059#issuecomment-331103236](https://github.com/sphinx-doc/sphinx/issues/4059#issuecomment-331103236)

**Comment by adityakeyal** [comment]
Resolved by uninstalling all versions of python and installing latest version.
